### ISSUE TITLE
Extensions page needs an update - shows install, even if installed

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/events-for-geodirectory#119]
![image](https://user-images.githubusercontent.com/114659/107785276-ab12a500-6d4c-11eb-8461-497b788b4bf8.png)

**Comment by alexrollin** [comment]
https://secure.helpscout.net/conversation/1426875450/14929/

![image](https://user-images.githubusercontent.com/114659/108069980-487b1b00-7064-11eb-8f37-660f58246755.png)

**Comment by kprajapatii** [comment]
Fixed

It will show "Install" button until next transient cache update.
