### ISSUE TITLE
Events enhancements - sorting option setup by default

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/events-for-geodirectory#131]
The sorting option for event dates should be a pre-defined default.
It should havea  nice tooltip that explains this is the main one people want for sorting events.
The sorting option for event dates ascending should be the default in the sorting options as soon as the events addon is installed.

**Comment by alexrollin** [comment]
we are getting LOTS of tickets from users reticent to get into the sorting options. Can we get this setup by default, just that much less work for our users.

Of note this option is available by default for shortcodes, we just need it showing in the UI and then selectable within GD Listings.

**Comment by alexrollin** [comment]
This would be nice to have. Many users still skipping this and writing in to ask why their events sort by latest published date instead of event date.

https://secure.helpscout.net/conversation/1823019899/30488/

**Comment by Stiofan** [comment]
**Dummy data installs the predefined sort options, let's instead make these install by default on install.**
