### ISSUE TITLE
Calendar view

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/events-for-geodirectory#135]
Make a 'full page' responsive calendar view with an option to show in a single column.

Option to show 

Today
Tomorrow
This week
Next week
This month (default)
Next month

Calendar should have

Month/week/day navigation (previous/next)
Option to switch to day/week/month view
Outline border color
Inner border color
Label text color
Option to choose an Agenda template type

**Comment by alexrollin** [comment]
https://secure.helpscout.net/conversation/1585313173/22559?folderId=3803506

**Comment by kprajapatii** [comment]
Moved to https://github.com/AyeCode/events-for-geodirectory/issues/16
