### ISSUE TITLE
GD Event Schedules - Option for showing recurring date parts on recurring events recurrences

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/events-for-geodirectory#136]
There is a missing feature

When viewing an instance/recurrence of a recurring event there isn't a way to show the date OF THAT PARTICULAR recurrance with GD Event Schedules

This should be an option for GD Event Schedules, that with one setting it shows the date of the original event and with another setting it will show the date of the recurrence. 

In this way users can use 2 GD Event schedules on a single listing, one to show the original, and one to show the current date of an event

**Comment by kprajapatii** [comment]
This can be achieved by using [gd_event_schedules] widget or may be gd post meta.
