### ISSUE TITLE
option for showing single ocrruence breaks sorting order

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/events-for-geodirectory#139]
This shows events in order.
[gd_listings event_type = "upcoming" post_type = "gd_event" post_limit = "100" add_location_filter = "1" sort_by = "event_dates_asc" title_tag = "h3" layout = "2" view_all_link = "1" bottom_pagination = "1" skin_id = " 0 "skin_column_gap =" 30 "skin_row_gap =" 35 "]

Add the option for single event and they are not in order anymore.
[gd_listings event_type="upcoming" single_event="1" post_type="gd_event" post_limit="100" sort_by="event_dates_asc" title_tag="h3" layout="2" view_all_link="1" bottom_pagination="1" skin_id="0" skin_column_gap="30" skin_row_gap="35"]

https://ppldb.com/v2/wp-admin/post.php?post=663&action=edit&classic-editor

**Comment by kprajapatii** [comment]
See https://secure.helpscout.net/conversation/1498058764/18522/#thread-4359276501
https://ppldb.com/v2/663-2/
