### ISSUE TITLE
Time formats for event schedules - bring over from post meta

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/events-for-geodirectory#159]
Our members want even more flexibility for event schedules widget
they seek to have the same data options as they get with gd post meta for the event schedules template output

This comes about in support as requests to hide the end date and time, common, or the solution that instead of using event schedules they must use post meta for their event date data output - but this will NOT work for the special cases for which event schedules was designed.

It would also be nice to have date parts, so the schedule template could be edited in a granular format more like the address parts in GD Post Address - we have regular requests for this.

![image](https://user-images.githubusercontent.com/114659/128210477-36b47503-b7a9-4b5b-b17f-a61287ace099.png)

![image](https://user-images.githubusercontent.com/114659/128210431-a7fad4e8-1539-4e91-80ac-e3c5fa68ae0c.png)

**Comment by alexrollin** [comment]
https://secure.helpscout.net/conversation/1590055814/22728/

**Comment by alexrollin** [comment]
https://secure.helpscout.net/conversation/1619139845/23936?folderId=3803591#modal

**Comment by kprajapatii** [comment]
Usage:

`function gd_snippet_get_schedule_templates( $templates ) {
	$templates[] = '{start_date} . {start_time}';

	return $templates;
}
add_filter( 'geodir_event_get_schedule_templates', 'gd_snippet_get_schedule_templates', 10, 1 );`
