### ISSUE TITLE
ER: recurring events feature request

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/events-for-geodirectory#190]
#1: Recurring events which lasts more than one day (e.g. 6 days) with user defined start dates (e.g. 5th of may, 14th of may, 20th of may) cannot be saved. It will only be shown as a one day lasting event. In the backend I choose duration of event = 6, but this is ignored by system and if I go back in edit mode it shows duration of event = 1.
https://secure.helpscout.net/conversation/1878610610/32118?folderId=3812058

_the task also have video attached_

**Comment by kprajapatii** [comment]
Fixed
