### ISSUE TITLE
ER Unpublish events X days after end date

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/events-for-geodirectory#58]
Over time several users have requested a way to remove events as unpublished after the end date.

The most recent
https://wpgeodirectory.com/support/topic/unpublish-delete-old-events/#post-517706

**Comment by Stiofan** [comment]
https://secure.helpscout.net/conversation/1570966191/21937?folderId=3803512

**Comment by Stiofan** [comment]
i think it might be a good idea to add a setting to unpublish x days after event ends, but this I guess would only work for non recurring? thoughts?
I think in some cases a email that sends when the event has ended would be enough.

**Comment by alexrollin** [comment]
I spent time on her other ticket this week

It would be ideal if packages could downgrade for an EVENT end date, as opposed to expire date.

https://secure.helpscout.net/conversation/1573346323/22031/

**Comment by alexrollin** [comment]
Another request for this
https://secure.helpscout.net/conversation/1579979065/22349/

**Comment by kprajapatii** [comment]
Option added under event CPT > Settings > General > Manage Past Events to handle expired events.
Added tool GeoDirectory > Status > Tools > Handle Past Events as well to manually run function to handle past events.

**Comment by alexrollin** [comment]
Option added under event CPT > Settings > General > Manage Past Events to handle expired events.
Added tool GeoDirectory > Status > Tools > Handle Past Events as well to manually run function to handle past events.


![image](https://user-images.githubusercontent.com/114659/127009347-54f6c276-c352-40b3-bb80-e16977956c1a.png)
