### ISSUE TITLE
Full page event calendar view

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/events-for-geodirectory#64]
We need this sooner rather than later
https://plantswap.org/events/month/
https://wpgeodirectory.com/support/topic/comparison-to-modern-tribes-events-plugin/
https://theeventscalendar.com/knowledgebase/k/embedding-calendar-views-with-the-tribe_events-shortcode/
https://theeventscalendar.com/showcase/
![Events Archive » PlantSwap org](https://user-images.githubusercontent.com/114659/73134198-1c918f80-4034-11ea-8004-437e7af86858.jpg)

**Comment by kprajapatii** [comment]
See https://github.com/AyeCode/events-for-geodirectory/issues/16
